# Generated by Django 5.2.15 on 2026-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('descripcion', models.TextField()),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
