# Generated by Django 5.2.15 on 2026-06-07 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=5)),
                ('numero', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('inhabilitada', 'Inhabilitada')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoConfiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('combo', 'Combo'), ('palomitas', 'Palomitas'), ('bebidas', 'Bebidas'), ('dulces', 'Dulces y Snacks')], max_length=20)),
                ('precio', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='confiteria/')),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('filas', models.IntegerField()),
                ('columnas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.butaca')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
            ],
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('precio', models.IntegerField()),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.funcion'),
        ),
        migrations.CreateModel(
            name='ItemConfiteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productoconfiteria')),
            ],
        ),
        migrations.AddField(
            model_name='butaca',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sala'),
        ),
    ]
