# Generated by Django 5.2.15 on 2026-06-08 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_butaca_productoconfiteria_sala_compra_entrada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='columnas',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='filas',
        ),
        migrations.AddField(
            model_name='sala',
            name='configuracion',
            field=models.JSONField(default=dict),
        ),
    ]
