# Generated by Django 5.2.15 on 2026-06-09 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_sala_columnas_remove_sala_filas_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('visitas', models.IntegerField(default=0)),
                ('puntos', models.FloatField(default=0)),
                ('categoria', models.CharField(choices=[('estandar', 'SOCIO BIO-Estandar'), ('silver', 'SOCIO BIO-Silver'), ('gold', 'SOCIO BIO-Gold')], default='estandar', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
