# Generated by Django 5.2.15 on 2026-06-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcion',
            name='tipo',
            field=models.CharField(choices=[('2d_doblada', '2D Doblada'), ('2d_subtitulada', '2D Subtitulada'), ('3d', '3D')], default='2d_doblada', max_length=20),
        ),
    ]
