# Generated by Django 5.2.15 on 2026-06-18 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_compra_invitado_y_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='funcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.funcion'),
        ),
    ]
