# Generated by Django 5.2.15 on 2026-06-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_compra_funcion_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoconfiteria',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
