# Generated by Django 5.2.15 on 2026-06-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='categoria',
            field=models.CharField(choices=[('clasico', 'CineBio Clásico'), ('plata', 'CineBio Plata'), ('oro', 'CineBio Oro'), ('black', 'CineBio Black')], default='clasico', max_length=20),
        ),
    ]
