# Generated by Django 5.2.15 on 2026-06-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_categorias_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='estado',
            field=models.CharField(choices=[('completada', 'Completada'), ('pendiente_devolucion', 'Pendiente de Devolución'), ('devuelta', 'Devuelta')], default='completada', max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='funcion_cancelada_info',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
