# Generated by Django 5.2.15 on 2026-06-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_estado_devolucion_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='tipo',
            field=models.CharField(choices=[('2d_doblada', '2D Doblada'), ('2d_subtitulada', '2D Subtitulada'), ('3d_doblada', '3D Doblada'), ('3d_subtitulada', '3D Subtitulada')], default='2d_doblada', max_length=20),
        ),
    ]
